# Generated by Django 3.1 on 2020-10-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('periodic', 'Periodic'), ('one_time', 'One time'), ('temporary', 'Temporary')], default='periodic', max_length=9)),
                ('period', models.CharField(choices=[('two_weeks', '2 weeks'), ('month', 'A month')], default='two_weeks', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('income', 'Income'), ('need', 'Need'), ('want', 'Want'), ('saving', 'Saving')], max_length=6)),
                ('value', models.FloatField(default=0)),
            ],
        ),
    ]
